### ISSUE TITLE
SyntaxError: Unexpected token (      app.get('*', async (req, res, next) => {    

### ISSUE THREAD

**Issue by trentin** [kriasoft/react-firebase-starter#281]
The latest version gives the following error when running 'yarn start'

app.get('*', async (req, res, next) => {
                   ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at global.appPromise.then (/Users/trentin/projects/ssr2/node_modules/react-app-tools/config/webpackDevServer.config.js:21:25)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by trentin** [comment]
Hi I found the issue, I was running an older version of Node.JS. 
Thanks
