### ISSUE TITLE
Windows 10 clean install startup issue - Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by DaveyEdwards** [kriasoft/react-firebase-starter#285]
This was tested on the newest version of react-firebase-starter.  
I have tried installing this on a Windows 10 PC and Laptop and both have the same issue, so I thought others may be seeing this.  (One had firebase credentials set, other did not)

On Windows 10 after doing:
```
yarn install
yarn relay // <- works and compiles fine
yarn start
```
it gives the following error:

```
λ yarn start
yarn run v1.3.2
$ react-app start
C:\Projects\myiworlds\react-firebase-starter\node_modules\react-scripts\config\webpack.config.dev.js:100
      process.env.NODE_PATH.split(path.delimiter).filter(Boolean)
                            ^

TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (C:\Projects\myiworlds\react-firebase-starter\node_modules\react-scripts\config\webpack.con

fig.dev.js:100:29)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Projects\myiworlds\react-firebase-starter\node_modules\react-scripts\config\webpackDevS

erver.config.js:14:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
```

**Comment by koistya** [comment]
What version of Node.js are you using?

>

**Comment by DaveyEdwards** [comment]
Node - 8.9.1

**Comment by tierfour** [comment]
@DaveyEdwards I was able to work around this by adding NODE_PATH environmental variables to both my local Windows machine and the .env file. 

Windows:
`NODE_PATH=%AppData%\npm\node_modules`

.env
`NODE_PATH=./`

So far I haven't had any issues with the starter kit base code but I'm just starting to implement features so we'll keep ya posted. Hope this helps!

**Comment by DaveyEdwards** [comment]
@tierfour Thank you that worked 

For those unsure how to set environment variables:

- Go to start menu and type in env and select "Edit the system environment variables" 
![image](https://user-images.githubusercontent.com/15203899/36939592-4458965e-1ee8-11e8-9ce8-16d8136fe5d5.png)

- Select Environment Variables
![image](https://user-images.githubusercontent.com/15203899/36939611-97d8cf9c-1ee8-11e8-9c5c-00d61e493d18.png)

- On the System Variables section click New
![image](https://user-images.githubusercontent.com/15203899/36939616-bb31e82a-1ee8-11e8-9a85-34d2c4265c1a.png)

- Type in variable name NODE_PATH
- And then browse Directory to your npm/node_modules file
![image](https://user-images.githubusercontent.com/15203899/36939621-db3cce96-1ee8-11e8-8467-11f355e43855.png)

**Comment by DaveyEdwards** [comment]
@koistya maybe we should make a note on the readme for Windows users to see this issue?
