### ISSUE TITLE
Issues when setting up on Windows

### ISSUE THREAD

**Issue by PabloMarch** [kriasoft/react-firebase-starter#309]
Hello Kriasoft team, first thanks by provide such complete starter project. I'm trying to set it up on Windows using PowerShell and all went perfect until I try to login on the UI, I'm receiving an error when use google account for sign in. This is the log:

>Warning, FIREBASE_CONFIG environment variable is missing. Initializing firebase-admin will fail 
error: relation "user_identities" does not exist
    at Connection.parseE (E:\Projects\qrbeer.com\serverless\node_modules\pg\lib\connection.js:553:11)
    at Connection.parseMessage (E:\Projects\qrbeer.com\serverless\node_modules\pg\lib\connection.js:378:19)
    at Socket.<anonymous> (E:\Projects\qrbeer.com\serverless\node_modules\pg\lib\connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
From previous event:
    at Client_PG._query (E:\Projects\qrbeer.com\serverless\node_modules\knex\lib\dialects\postgres\index.js:287:12)
    at Client_PG.query (E:\Projects\qrbeer.com\serverless\node_modules\knex\lib\client.js:206:17)
    at Runner.<anonymous> (E:\Projects\qrbeer.com\serverless\node_modules\knex\lib\runner.js:155:36)
From previous event:
    at E:\Projects\qrbeer.com\serverless\node_modules\knex\lib\runner.js:61:21
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Runner.run (E:\Projects\qrbeer.com\serverless\node_modules\knex\lib\runner.js:47:31)
    at Builder.Target.then (E:\Projects\qrbeer.com\serverless\node_modules\knex\lib\interface.js:39:43)
    at process._tickCallback (internal/process/next_tick.js:188:7)

At this point I have everything setup and running, I just changed a line of code on '\scripts\setup.js' to get it to work on Windows (line 14, add the shell support otherwise status return always null):
`({ status } = cp.spawnSync('yarn', ['install'], { stdio: 'inherit', shell: true }));`

And this is the database tables:

>postrgres=# \dt
              List of relations
 Schema |      Name       | Type  |  Owner
--------+-----------------+-------+----------
 public  | migrations         | table  | postgres
 public  | migrations_lock | table  | postgres
(2 rows)

**Comment by koistya** [comment]
It seems like `yarn db-migrate` failed to read schema from `migrations/20180101000000_initial.js`, this file is using `async/await` so it only works with Node.js 8 and higher. What error do you get when your run this command?

BTW, if you need to migrate production database, you can put connection info to `.env.production` or `.env.production.local` file and run `yarn db-migrate --env=prod`.

**Comment by PabloMarch** [comment]
@koistya, yarn migrate works fine, it's complete the task:

> yarn db-migrate
yarn run v1.6.0
$ knex migrate:latest
Batch 1 run: 1 migrations
E:\Projects\qrbeer.com\serverless\migrations\20180101000000_initial.js
Done in 6.83s.

The one that was printing a warning is 'yarn db', I change the code page of the console updating the db script on the package.json:
`"db": "chcp 1252 && node ./scripts/db",`

I don't get it to run in windows yet but if I make any progress I'll be posting solutions here, one other thing I had to before was to run 'yarn -g firebase-tools' and add ´C:\Program Files\PostgreSQL\10\bin´ along with watchman to $PATH variables.

**Comment by PabloMarch** [comment]
I got it, there were other calls to `cp.spawnSync` to run it just be sure to add `shell: true` to the options sent

**Comment by gregoryanm** [comment]
Well, thank goodness for this post is here....

**Comment by TrySpace** [comment]
Same issue with windows `relation "user_identities" does not exist` here

I get:
```
$ yarn db-migrate
yarn run v1.7.0
$ knex migrate:latest
Already up to date
Done in 1.73s.
```

I'm missing the `Batch 1 run: 1 migrations / xxxxx\migrations\20180101000000_initial.js` part

How did you solve it in the end?

**Comment by koistya** [comment]
@TrySpace what happens if you rollback the latest migration and apply it over again? Also, check if database connection settings are correct (in `.env` file)

```bash
$ yarn db-rollback     # Rolls back the latest migration
$ yarn db-migrate      # Applies all the pending migrations (from `migrations` folder)
```
