### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Jakobovski** [kriasoft/react-firebase-starter#313]
On a fresh install i get the following issues when running `yarn start`. I tried a few things to no success.

Warning, FIREBASE_CONFIG environment variable is missing. Initializing firebase-admin will fail
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object../src/app.node.js (/Users/Jackson/development/getheardnow/build/app.js:792:82)
    at __webpack_require__ (/Users/Jackson/development/getheardnow/build/app.js:645:30)
    at /Users/Jackson/development/getheardnow/build/app.js:713:55
    at Object.<anonymous> (/Users/Jackson/development/getheardnow/build/app.js:716:10)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at global.appPromise.then (/Users/Jackson/development/getheardnow/node_modules/react-app-tools/config/webpackDevServer.config.js:92:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Jakobovski** [comment]
I figured out the problem. I needed to remove the newlines in my FIREBASE_SERVICE_KEY
