### ISSUE TITLE
Issues with postgres connectivity running in dev mode

### ISSUE THREAD

**Issue by mrtinkz** [kriasoft/react-firebase-starter#761]
Has anyone seen this before, I have the postgres running locally, I am able to connect to it through other db clients but not through the app, any thoughts what am I doing wrong?

```
$ yarn setup
yarn run v1.22.5
$ node ./scripts/setup
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
Environment: dev
SubError [TimeoutError]: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /Users/vpal/Documents/GitHub/evaluate/react-firebase-starter/node_modules/knex/lib/client.js:348:17
    at tryCatcher (/Users/vpal/Documents/GitHub/evaluate/react-firebase-starter/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/vpal/Documents/GitHub/evaluate/react-firebase-starter/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/Users/vpal/Documents/GitHub/evaluate/react-firebase-starter/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/vpal/Documents/GitHub/evaluate/react-firebase-starter/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/vpal/Documents/GitHub/evaluate/react-firebase-starter/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/vpal/Documents/GitHub/evaluate/react-firebase-starter/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/vpal/Documents/GitHub/evaluate/react-firebase-starter/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/vpal/Documents/GitHub/evaluate/react-firebase-starter/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/vpal/Documents/GitHub/evaluate/react-firebase-starter/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/vpal/Documents/GitHub/evaluate/react-firebase-starter/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/vpal/Documents/GitHub/evaluate/react-firebase-starter/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:458:21) {
  sql: 'SELECT 1 FROM pg_database WHERE datname = ?',
  bindings: [ 'app' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mrtinkz** [comment]
I figured it out, it was the node 14 and knex versions issue, upgrading the knex version fixed the problems.
